[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "pip"]

[phases.install]
cmds = [
    "npm ci",
    "pip install --upgrade pip", 
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build",
    "cp -r dist/* static/"
]

[start]
cmd = "python app.py"